# Generated by Django 3.2.25 on 2025-04-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tutor_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ornaments_and_ornament',
            new_name='ornaments_and_costume',
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
