# Generated by Django 3.2.25 on 2025-04-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250417_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='order_tb',
            name='ORNAMENTS_AND_COSTUME',
        ),
        migrations.AddField(
            model_name='order_sub',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order_tb'),
            preserve_default=False,
        ),
    ]
