# Generated by Django 3.2.25 on 2025-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250417_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume_and_ornaments_booking',
            name='total_amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
