# Generated by Django 3.2.25 on 2025-04-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_costume_and_ornaments_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornaments_and_costume',
            name='CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
            preserve_default=False,
        ),
    ]
