# Generated by Django 3.2.25 on 2025-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ornaments_and_costume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='payment_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tb',
            name='payment_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
